/******************************************************************************
* File Name:   main.c
*
* Description: This is the source code for the XMC MCU: CCU8 capture Example
*              for ModusToolbox.
*
* Related Document: See README.md
*
******************************************************************************
*
* Copyright (c) 2015-2022, Infineon Technologies AG
* All rights reserved.                        
*                                             
* Boost Software License - Version 1.0 - August 17th, 2003
* 
* Permission is hereby granted, free of charge, to any person or organization
* obtaining a copy of the software and accompanying documentation covered by
* this license (the "Software") to use, reproduce, display, distribute,
* execute, and transmit the Software, and to prepare derivative works of the
* Software, and to permit third-parties to whom the Software is furnished to
* do so, all subject to the following:
* 
* The copyright notices in the Software and this entire statement, including
* the above license grant, this restriction and the following disclaimer,
* must be included in all copies of the Software, in whole or in part, and
* all derivative works of the Software, unless such copies or derivative
* works are solely in the form of machine-executable object code generated by
* a source language processor.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
* SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
* FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
* ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
* DEALINGS IN THE SOFTWARE.
*                                                                              
*****************************************************************************/
#include <stdio.h>
#include "cybsp.h"
#include "cy_utils.h"
#include "cy_retarget_io.h"

/*******************************************************************************
* Macros
*******************************************************************************/

#define CAPTURE_VALUE_EVENT0                    1
#define CAPTURE_VALUE_EVENT1                    3

/* Define macro to enable/disable printing of debug messages */
#define ENABLE_XMC_DEBUG_PRINT (0)

/* Define macro to set the loop count before printing debug messages */
#if ENABLE_XMC_DEBUG_PRINT
#define DEBUG_LOOP_COUNT_MAX                    2
#endif

/*******************************************************************************
* Function Name: main
********************************************************************************
* Summary:
* This is the main function. It configures one of the CCU8 PWM slices to 
* generate a PWM output signal, and another slice to capture the timer value
* at every rising edge and falling edge of the capture trigger signal. In this 
* project PWM output from first slice is used as capture trigger for second 
* slice.
*
* Output:
* This example project will print the capture value from second CCU8 slice at
* every rising and falling edge of the PWM signal. 
* 
* Parameters:
*  none
*
* Return:
*  int
*
*******************************************************************************/
int main(void)
{
    cy_rslt_t result;

    uint16_t captureVal = 0;

    #if ENABLE_XMC_DEBUG_PRINT
    /* Assign false to disable printing of debug messages */
    static volatile bool debug_printf = true;

    /* Initialize the current loop count to zero */
    static uint32_t debug_loop_count = 0;
    #endif

    /* Initialize the device and board peripherals */
    result = cybsp_init();
    if (result != CY_RSLT_SUCCESS)
    {
        CY_ASSERT(0);
    }

    cy_retarget_io_init(CYBSP_DEBUG_UART_HW);

    #if ENABLE_XMC_DEBUG_PRINT
    printf("Initialization done\r\n");
    #endif

    for (;;)
    {
        /* Continuously poll for Capture events 0 and 1 */
        if(XMC_CCU8_SLICE_GetEvent(CAPTURE_SLICE_HW, XMC_CCU8_SLICE_IRQ_ID_EVENT0))
        {
            XMC_CCU8_SLICE_ClearEvent(CAPTURE_SLICE_HW, XMC_CCU8_SLICE_IRQ_ID_EVENT0);
            captureVal = XMC_CCU8_SLICE_GetCaptureRegisterValue(CAPTURE_SLICE_HW, CAPTURE_VALUE_EVENT0);
            #if !(ENABLE_XMC_DEBUG_PRINT)
            printf("Rising edge:%d\r\n", captureVal);
            #endif
        }

        if(XMC_CCU8_SLICE_GetEvent(CAPTURE_SLICE_HW, XMC_CCU8_SLICE_IRQ_ID_EVENT1))
        {
            XMC_CCU8_SLICE_ClearEvent(CAPTURE_SLICE_HW, XMC_CCU8_SLICE_IRQ_ID_EVENT1);
            captureVal = XMC_CCU8_SLICE_GetCaptureRegisterValue(CAPTURE_SLICE_HW, CAPTURE_VALUE_EVENT1);
            #if !(ENABLE_XMC_DEBUG_PRINT)
            printf("Falling edge:%d\r\n", captureVal);
            #endif

            #if ENABLE_XMC_DEBUG_PRINT
            debug_loop_count++;

            if(debug_printf && debug_loop_count == DEBUG_LOOP_COUNT_MAX )
            {
                debug_printf = false;

                /* Print message after the loop has run after DEBUG_LOOP_COUNT_MAX times */
                printf("Capture values printed\r\n");
            }
            #endif
        }
    }
}

/* [] END OF FILE */
